[formatter.just]
command = "just"
options = ["--unstable", "--fmt", "--justfile"]
includes = ["justfile"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.js", "*.jsx", "*.ts", "*.tsx", "*.json", "*.md", "*.yaml", "*.yml"]
excludes = ["node_modules/**", "pnpm-lock.yaml"]

[formatter.shell]
command = "shfmt"
options = ["-i", "2", "-ci", "-s", "-w"]
includes = ["*.sh", "*.bash"]
